### PR TITLE
Fix pipeline promise and handle errors

### LINKED ISSUE #20: [bug] Emit returns integer
Emit returns integer values, I think the bug is caused by:

https://github.com/mcollina/mqemitter-redis/blob/b7bfa6b0e6a5af86380083a38b5d7b901ac69a32/mqemitter-redis.js#L143

### PR DESCRIPTION
**Pull request by robertsLando**
Fixes #20 #15

### CODE REVIEW

File: mqemitter-redis.js [hunk 1]
```diff
@@ -139,10 +140,11 @@ MQEmitterRedis.prototype.emit = function (msg, done) {
   }
 
   const p = this._pipeline.publish(msg.topic, msgpack.encode(packet))
+
   if (done) {
-    p.then(done, done)
+    p.then(() => done()).catch(done)
```
Comment (mcollina) [inline mqemitter-redis.js]: Why is this needed?

```suggestion
    p.then(() => done(), done)
```

File: mqemitter-redis.js [hunk 2]
```diff
@@ -139,10 +140,11 @@ MQEmitterRedis.prototype.emit = function (msg, done) {
...
   } else {
-    p.catch(noop)
+    p.catch(this._onError.bind(this))
```
Comment (mcollina) [inline mqemitter-redis.js]: we should probably maintain a bound `_onError`, as this would be called a lot.

Comment (robertsLando) [reply mqemitter-redis.js]: So just `this._onError` here?

File: mqemitter-redis.js (hunk 1 above)
Comment (robertsLando) [reply mqemitter-redis.js]: `p.then(() => done()`

Is used because `p.then` returns an integer that is treated in done as an error with the previous signature.

File: mqemitter-redis.js (hunk 2 above)
Comment (mcollina) [reply mqemitter-redis.js]: yes, but you'd need to to `this._onError = this._onError.bind(this)`

File: mqemitter-redis.js (hunk 1 above)
Comment (mcollina) [reply mqemitter-redis.js]: ok perfect.

**Comment by robertsLando** [comment]
@mcollina Tests are fine but I see a rejection error. 

```
# without any listeners
  ok 12 reset the current messages trackers(node:4910) UnhandledPromiseRejectionWarning: Error: Connection is closed.
    at /media/daniel/DATA/Git-Projects/mqemitter-redis/node_modules/ioredis/built/connectors/StandaloneConnector.js:50:28
    at processTicksAndRejections (internal/process/task_queues.js:76:11)
(node:4910) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4910) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the ✓ without any listenersnon-zero exit code.
```

That rejection is thrown when `emit` throws error

**Comment by mcollina** [comment]
Code looks good, but the unhandledRejection should be fixed.

**Comment by robertsLando** [comment]
@mcollina Now it is fixed! This fix #15

**Comment by robertsLando** [comment]
@mcollina Please make a new release after this merge so I can also fix this in `aedes-persistence-redis`

File: mqemitter-redis.js [hunk 3]
```diff
@@ -14,7 +14,8 @@ function MQEmitterRedis (opts) {
     return new MQEmitterRedis(opts)
   }
 
-  opts = opts || {}
+  opts = opts || { showFriendlyErrorStack: true }
```
Comment (mcollina) [inline mqemitter-redis.js]: why this change?

Comment (robertsLando) [reply mqemitter-redis.js]: Sorry, missed it, was to identify where the unhandled rejection was coming from.

**Comment by robertsLando** [comment]
@mcollina Could you review this and if ok merge and release a new version? So I can go on with aedes-persistence-redis PR

File: mqemitter-redis.js [hunk 4]
```diff
@@ -54,15 +63,15 @@ function MQEmitterRedis (opts) {
   })
 
   this.subConn.on('error', function (err) {
-    that.state.emit('error', err)
+    that.state.emit('connectionError', err)
```
Comment (mcollina) [inline mqemitter-redis.js]: Why this became `connectionError`? The use of `error` was intentional to crash the mqemitter.

Comment (robertsLando) [reply mqemitter-redis.js]: Fixed

File: mqemitter-redis.js [hunk 5]
```diff
@@ -33,6 +34,14 @@ function MQEmitterRedis (opts) {
 
   var that = this
 
+  function onError (err) {
+    if (err) {
+      that.state.emit('emitError', err)
```
Comment (mcollina) [inline mqemitter-redis.js]: why its this not `error`?

Comment (robertsLando) [reply mqemitter-redis.js]: @mcollina Because it I make this 'error' I get unhandled rejections from emit, check #15

Comment (mcollina) [reply mqemitter-redis.js]: I think we need to track down why this is happening wqithout changing event name.

Comment (robertsLando) [reply mqemitter-redis.js]: @mcollina I have no clue Matteo... I have try to debug this but I can only tell you when this happens:

If emit throws an error and cb is not defined the unhandled rejection is thrown after I call `this.state.emit('error')`,  can that emit throw an error?

Comment (robertsLando) [reply mqemitter-redis.js]: Ok I have found this in docs: https://nodejs.org/api/events.html#events_class_events_eventemitter

**Comment by mcollina** [comment]
The problem is not avoiding the unhandledRejection, but rather understading where it come from and handle it there.

**Comment by robertsLando** [comment]
@mcollina It comes from: https://github.com/mcollina/mqemitter/blob/master/abstractTest.js#L139

Close is called immediatly after emit and this causes that error. Should I fix that test?

**Comment by mcollina** [comment]
Which operation is missing a `catch()` handler? That's what is not clear to me.

**Comment by robertsLando** [comment]
Please check my prev comment https://github.com/mcollina/mqemitter-redis/pull/21#discussion_r385634852

**Comment by mcollina** [comment]
Which promise is rejecting? Which line of code creates that promise? Why does it not have a .catch() handler attached?

**Comment by robertsLando** [comment]
@mcollina This is the promise:

File: mqemitter-redis.js [hunk 6]
```diff
@@ -33,6 +34,17 @@ function MQEmitterRedis (opts) {
 
   var that = this
 
+  function onError (err) {
```
Comment (mcollina) [inline mqemitter-redis.js]: If the mqemitter is closed, you should ignore the error.

File: mqemitter-redis.js [hunk 7]
```diff
@@ -33,6 +34,17 @@ function MQEmitterRedis (opts) {
...
+    if (err) {
+      that.state.emit('error', err)
+    }
+  }
+
+  // Add default error listener to prevent unhandled rejection #15
+  this.state.on('error', noop)
```
Comment (mcollina) [inline mqemitter-redis.js]: remove this.

**Comment by robertsLando** [comment]
@mcollina Remember to create a release after the merge so I can go on with aedes-persistence-redis :smile:
